services:
  db:
    container_name: mysql
    tty: true
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 10s
      # timeout: 5s
      # retries: 5
  backend:
    container_name: golang
    tty: true
    build:
      context: ./Go/data
      dockerfile: ../Dockerfile
      args:
        USERNAME: ${BACK_USER}
        PASSWORD: ${BACK_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./Go/src:/home/${BACK_USER}/app
    # depends_on:
      # db:
        # condition: service_healthy
    # healthcheck:
      # test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      # interval: 10s
      # timeout: 5s
      # retries: 5
  frontend:
    container_name: react
    tty: true
    build:
      context: ./React/src
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./React/src:/home/node/app
      - node_modules:/home/node/app/node_modules
    # depends_on:
      # backend:
        # condition: service_healthy
volumes:
  node_modules:
  mysql_data: